Replace uses of builtin substitution with custom semantics for lambda
runtimeverification/pl-tutorial pull request #3
Opened 2024-01-23 22:46 UTC by gtrepta

This replaces the substitution function `E[V / X]` from the `SUBSTITUTION` module with manually defined semantics for it in the lambda lessons. It's possible that the `SUBSTITUTION` module will eventually be dropped from K, so this PR is the beginning of preparation/discovery for making such a change.

Notes:
- The `binder` attribute and `KVar` hooked sort from `substitution.md` is still being used for renaming variables that have duplicate names. Without them, then the free variable capture example (`a (((lambda x.lambda y.x) y) z)`) will evaluate incorrectly to `a z` instead of `a y`. @ehildenb Is there an alternative option here?
- The lesson texts are still teaching and referring to the builtin substitution, and need to be rewritten.

2024-01-24 03:06 UTC, Scott-Guest requested changes
It's a bit tedious, but I'd recommend fixing the variable capture issue by manually alpha-converting as needed.

This would look something like
```
// Produce a fresh var which does not occur in the set
syntax Id ::= freshFrom(Set) [function]
rule freshFrom(S) => #if !I:Id in S #then freshFrom(S) #else I #fi

// Collect all the free variables in a term
syntax Set ::= freeVars(Exp) [function]

rule (lambda X . E) [_ / X] => lambda X . E
rule (lambda X . E) [V / Y] => lambda X . (E [V / Y]) requires (X =/=K Y) andBool (notBool (X in freeVars(V)))
rule (lambda X . E) [V / Y] => #let Z = freshFrom(freeVars(V) freeVars(E)) #in (lambda Z (E [Z / X] [V / Y])) [owise]
```

Alternatively, we could use DeBruijn indices or a locally nameless representation. This is conceptually clearer, but would require converting between the program syntax and the internal representation using these indices.

2024-01-24 13:39 UTC, Baltoli commented
Indeed; the "pure K" solution implemented here will need a way of dealing with alpha-conversion. I think for the purposes of _this language_, we can do so explicitly rather than implementing locally nameless / de bruijn indices etc.

2024-01-29 20:08 UTC, gtrepta commented
I've updated this to use custom semantics for alpha conversion. Note that I haven't updated lesson documentation yet because we can revert this back to using the substitution module if we implement the frontend pass to generate these semantics.

2024-01-29 22:18 UTC, Scott-Guest approved these changes
LGTM. I'd open an issue to note that we still have to update the documentation.

2024-01-30 09:00 UTC, Baltoli commented
https://github.com/runtimeverification/pl-tutorial/issues/5

2024-01-30 09:00 UTC, Baltoli approved these changes

2024-01-30 09:03 UTC, merged